version: '3.8'

services:
  aggregator:
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    container_name: aggregator
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - async-aggregator-network

  resource1:
    build:
      context: ./resource
      dockerfile: Dockerfile
    container_name: resource1
    environment:
      - RESOURCE_ID=resource-1
    networks:
      - async-aggregator-network

  resource2:
    build:
      context: ./resource
      dockerfile: Dockerfile
    container_name: resource2
    environment:
      - RESOURCE_ID=resource-2
    networks:
      - async-aggregator-network

  resource3:
    build:
      context: ./resource
      dockerfile: Dockerfile
    container_name: resource3
    environment:
      - RESOURCE_ID=resource-3
    networks:
      - async-aggregator-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "8082:8082"
    depends_on:
      - aggregator
    networks:
      - async-aggregator-network

networks:
  async-aggregator-network:
    driver: bridge
