server:
  port: 8080

spring:
  application:
    name: aggregator

aggregator:
  callback:
    url: http://aggregator:8080/aggregate/callback

resource:
  urls: http://resource1:8081,http://resource2:8081,http://resource3:8081

logging:
  level:
    se.inera.asyncaggregator: DEBUG
